// All site copy, in English and Turkish. Everything here is real: it comes from Adem's CV
// and his approved LinkedIn texts. No invented numbers, jobs or awards.

export const UI = {
  en: {
    'meta.title': 'Adem Batur — Computer Engineer | AI Agents | Humanoid Robotics',
    'meta.description':
      'Adem Batur — Computer Engineering student at Sakarya University. TEKNOFEST 2026 AI in Aviation finalist, TÜBİTAK 2209-B principal investigator. Perception, GPS-denied positioning, AI agents and Flutter apps.',
    'skip': 'Skip to content',
    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.experience': 'Experience',
    'nav.contact': 'Contact',
    'nav.cv': 'CV',
    'nav.lang': 'Türkçe',
    'nav.langAria': 'Switch language to Turkish',
    'hero.kicker': 'Sakarya University · Computer Engineering · Türkiye',
    'hero.tagline': 'Computer Engineer | AI Agents | Humanoid Robotics',
    'hero.sub':
      'Third-year Computer Engineering student. I build the pieces a humanoid robot needs — perception, self-localisation and agents that act — and measure every fix.',
    'hero.cta1': 'See projects',
    'hero.cta2': 'Download CV',
    'hero.scroll': 'Scroll',
    'hero.hint': 'Move your pointer to turn the portrait',
    'hero.alt': 'Point-cloud portrait of Adem Batur built from a photo with monocular depth estimation',
    'hl.title': 'Highlights',
    'hl.1v': 'Finalist',
    'hl.1l': 'TEKNOFEST 2026 AI in Aviation · Team NURON, captain',
    'hl.2v': '2nd',
    'hl.2l': 'online simulation round, which drew 150+ teams',
    'hl.3v': '~1.6 m',
    'hl.3l': 'horizontal error over 1,800 GPS-denied frames',
    'hl.4v': '98.8%',
    'hl.4l': 'RGB–thermal reference-matching precision',
    'hl.5v': '2209-B',
    'hl.5l': 'TÜBİTAK research grant · principal investigator',
    'hl.6v': '3.48',
    'hl.6l': 'GPA out of 4.00 · Sakarya University',
    'hl.7v': '700+',
    'hl.7l': 'automated tests in Dotnote, my Flutter app',
    'about.kicker': 'About',
    'about.title': 'Building towards brain-like minds for humanoid robots.',
    'about.p1':
      "I'm a third-year Computer Engineering student at Sakarya University (GPA 3.48/4.00) with a minor in Control & Automation. My long-term goal is to build brain-like intelligence for humanoid robots, and I learn by building the pieces such a robot needs: perception, self-localisation and agents that act.",
    'about.p2':
      'I care about why a method works, not only that it runs: I trace failures to their root cause and measure every fix — corrupt frames 9% → 0%, worst-case position error 982 m → 6.4 m.',
    'about.p3':
      'Open to research collaborations in AI & robotics and a 2027 internship in humanoid robotics or perception.',
    'about.cardCaption': 'My GitHub profile card — an ASCII portrait drawn from the same photo, rebuilt daily by GitHub Actions.',
    'about.photoAlt': 'Adem Batur, portrait photo',
    'projects.kicker': 'Projects',
    'projects.title': 'Things I actually built.',
    'projects.sub': 'Each card opens a detail view with real results, media and the code when it is public.',
    'projects.open': 'Open details',
    'projects.code': 'Code',
    'projects.site': 'Website',
    'projects.close': 'Close',
    'projects.role': 'Role',
    'projects.period': 'Period',
    'projects.stack': 'Stack',
    'projects.media': 'Media',
    'projects.illustration': 'Illustration',
    'projects.video': 'Video',
    'exp.kicker': 'Experience',
    'exp.title': 'Where the work happened.',
    'edu.kicker': 'Education',
    'edu.title': 'Education',
    'honors.kicker': 'Honors',
    'honors.title': 'Honors & awards',
    'skills.kicker': 'Skills',
    'skills.title': 'Tools I work with',
    'contact.kicker': 'Contact',
    'contact.title': "Let's build something.",
    'contact.sub':
      'Research collaborations in AI & robotics, a 2027 internship in humanoid robotics or perception — or just to talk about a project.',
    'contact.email': 'Email',
    'contact.cv': 'Download CV (PDF)',
    'contact.cvNote': 'English · 1 page · no phone number',
    'footer.built': 'Built with Three.js, a point cloud of my own photo and real results only.',
    'footer.source': 'Source on GitHub',
    'present': 'present',
    'nowebgl': 'Your browser does not support WebGL, so here is a still image of the 3D portrait.',
  },
  tr: {
    'meta.title': 'Adem Batur — Bilgisayar Mühendisi | Yapay Zekâ Ajanları | İnsansı Robotik',
    'meta.description':
      'Adem Batur — Sakarya Üniversitesi Bilgisayar Mühendisliği öğrencisi. TEKNOFEST 2026 Havacılıkta Yapay Zekâ finalisti, TÜBİTAK 2209-B proje yürütücüsü. Algılama, GPS’siz konum kestirimi, yapay zekâ ajanları ve Flutter uygulamaları.',
    'skip': 'İçeriğe geç',
    'nav.about': 'Hakkımda',
    'nav.projects': 'Projeler',
    'nav.experience': 'Deneyim',
    'nav.contact': 'İletişim',
    'nav.cv': 'CV',
    'nav.lang': 'English',
    'nav.langAria': 'Dili İngilizceye çevir',
    'hero.kicker': 'Sakarya Üniversitesi · Bilgisayar Mühendisliği · Türkiye',
    'hero.tagline': 'Bilgisayar Mühendisi | Yapay Zekâ Ajanları | İnsansı Robotik',
    'hero.sub':
      'Bilgisayar Mühendisliği 3. sınıf öğrencisiyim. İnsansı bir robotun ihtiyaç duyduğu parçaları — algılama, kendi konumunu bulma ve harekete geçen ajanlar — inşa ediyor, her düzeltmeyi ölçüyorum.',
    'hero.cta1': 'Projelere bak',
    'hero.cta2': 'CV indir',
    'hero.scroll': 'Kaydır',
    'hero.hint': 'Portreyi çevirmek için imleci hareket ettirin',
    'hero.alt': 'Adem Batur’un fotoğrafından tek kameralı derinlik kestirimiyle üretilmiş nokta bulutu portresi',
    'hl.title': 'Öne çıkanlar',
    'hl.1v': 'Finalist',
    'hl.1l': 'TEKNOFEST 2026 Havacılıkta Yapay Zekâ · NURON takımı, kaptan',
    'hl.2v': '2.',
    'hl.2l': '150’den fazla takımın katıldığı çevrim içi simülasyon turunda',
    'hl.3v': '~1,6 m',
    'hl.3l': 'GPS’siz 1.800 karede yatay hata',
    'hl.4v': '%98,8',
    'hl.4l': 'RGB–termal referans eşleştirme kesinliği',
    'hl.5v': '2209-B',
    'hl.5l': 'TÜBİTAK araştırma desteği · proje yürütücüsü',
    'hl.6v': '3,48',
    'hl.6l': '4,00 üzerinden GNO · Sakarya Üniversitesi',
    'hl.7v': '700+',
    'hl.7l': 'Flutter uygulamam Dotnote’ta otomatik test',
    'about.kicker': 'Hakkımda',
    'about.title': 'İnsansı robotlar için beyin benzeri bir zekâya doğru.',
    'about.p1':
      'Sakarya Üniversitesi Bilgisayar Mühendisliği 3. sınıf öğrencisiyim (GNO 3,48/4,00) ve Elektrik-Elektronik Mühendisliği Kontrol ve Otomasyon yan dalı yapıyorum. Uzun vadeli hedefim insansı robotlar için beyin benzeri bir zekâ geliştirmek; bunu, böyle bir robotun ihtiyaç duyduğu parçaları tek tek inşa ederek öğreniyorum: algılama, kendi konumunu bulma ve harekete geçen ajanlar.',
    'about.p2':
      'Bir yöntemin yalnızca çalışmasıyla değil, neden çalıştığıyla ilgileniyorum: hataları kök nedenine kadar izliyor ve her düzeltmeyi ölçüyorum — bozuk kareler %9 → %0, en kötü konum hatası 982 m → 6,4 m.',
    'about.p3':
      'Yapay zekâ ve robotik alanında araştırma iş birliklerine ve insansı robotik ya da algılama alanında 2027 stajına açığım.',
    'about.cardCaption': 'GitHub profil kartım — aynı fotoğraftan çizilen ASCII portre, GitHub Actions ile her gün yeniden üretiliyor.',
    'about.photoAlt': 'Adem Batur, portre fotoğrafı',
    'projects.kicker': 'Projeler',
    'projects.title': 'Gerçekten yaptıklarım.',
    'projects.sub': 'Her kart gerçek sonuçlar, medya ve (açıksa) kodun bulunduğu bir ayrıntı görünümü açar.',
    'projects.open': 'Ayrıntıları aç',
    'projects.code': 'Kod',
    'projects.site': 'Web sitesi',
    'projects.close': 'Kapat',
    'projects.role': 'Rol',
    'projects.period': 'Dönem',
    'projects.stack': 'Teknolojiler',
    'projects.media': 'Medya',
    'projects.illustration': 'İllüstrasyon',
    'projects.video': 'Video',
    'exp.kicker': 'Deneyim',
    'exp.title': 'İşin yapıldığı yerler.',
    'edu.kicker': 'Eğitim',
    'edu.title': 'Eğitim',
    'honors.kicker': 'Ödüller',
    'honors.title': 'Onurlar ve ödüller',
    'skills.kicker': 'Yetenekler',
    'skills.title': 'Çalıştığım araçlar',
    'contact.kicker': 'İletişim',
    'contact.title': 'Birlikte bir şey inşa edelim.',
    'contact.sub':
      'Yapay zekâ ve robotikte araştırma iş birliği, insansı robotik ya da algılama alanında 2027 stajı — ya da sadece bir proje hakkında konuşmak için.',
    'contact.email': 'E-posta',
    'contact.cv': 'CV indir (PDF)',
    'contact.cvNote': 'İngilizce · 1 sayfa · telefon numarası yok',
    'footer.built': 'Three.js, kendi fotoğrafımdan üretilmiş bir nokta bulutu ve yalnızca gerçek sonuçlarla yapıldı.',
    'footer.source': 'Kaynak kodu GitHub’da',
    'present': 'devam ediyor',
    'nowebgl': 'Tarayıcınız WebGL desteklemiyor; bu yüzden 3B portrenin sabit bir görüntüsü gösteriliyor.',
  },
};

export const LINKS = {
  github: 'https://github.com/adembtr',
  linkedin: 'https://www.linkedin.com/in/adem-batur-652188265',
  email: 'baturadem09@gmail.com',
  elifapps: 'https://elifapps.com/',
  dotnote: 'https://elifapps.com/apps/dotnote/',
  cv: '/assets/pdf/Adem_Batur_CV.pdf',
  source: 'https://github.com/adembtr/adembtr.github.io',
};

// ---------------------------------------------------------------------------- projects
// media: { type: 'video'|'image', src, poster, alt:{en,tr}, flag? }
export const PROJECTS = [
  {
    id: 'nuron',
    featured: true,
    accent: '#7fb4ff',
    title: { en: 'NURON', tr: 'NURON' },
    subtitle: {
      en: 'Perception & GPS-denied positioning for UAV imagery · TEKNOFEST 2026 AI in Aviation finalist',
      tr: 'İHA görüntülerinde algılama ve GPS’siz konum kestirimi · TEKNOFEST 2026 Havacılıkta Yapay Zekâ finalisti',
    },
    period: { en: '2025 – 2026', tr: '2025 – 2026' },
    role: {
      en: 'Team captain & AI developer (two-person team) — I selected the models and wrote the algorithms.',
      tr: 'Takım kaptanı ve yapay zekâ geliştiricisi (iki kişilik takım) — modelleri ben seçtim, algoritmaları ben yazdım.',
    },
    summary: {
      en: 'One offline pipeline that solves object detection, GPS-denied positioning and RGB/thermal reference-object matching on a single frame stream, on a single 8 GB GPU.',
      tr: 'Nesne tespiti, GPS’siz konum kestirimi ve RGB/termal referans nesne eşleştirmesini tek bir kare akışı üzerinde, tek bir 8 GB GPU’da çözen çevrim dışı bir boru hattı.',
    },
    bullets: {
      en: [
        'Three competition tasks on one frame stream, fully offline on a single 8 GB GPU, at 0.52–0.86 s per frame (22–36% of the time budget).',
        'GPS-denied positioning with DPVO visual odometry, loop closure and Umeyama alignment: ~1.6 m horizontal error over the 1,800 frames after GPS is cut, on a local replica of the competition server.',
        'Reference-object matching across RGB and thermal video (SAM 2 + DINOv3): 98.8% precision.',
        'Object detection with YOLO26 and landing-zone anomaly detection with PaDiM; vehicle-motion accuracy raised from 0.946 to 0.985.',
        'Root-cause fixes: an atomic inter-process frame hand-off cut corrupt frames from 9% to 0%; a calibration confidence gate cut the worst session’s error from 982 m to 6.4 m.',
        'Online simulation round: 2nd place (score 61.12) in a round that drew 150+ teams; on-site finals in September 2026.',
      ],
      tr: [
        'Üç yarışma görevi tek bir kare akışında, tamamen çevrim dışı, tek bir 8 GB GPU üzerinde; kare başına 0,52–0,86 sn (zaman bütçesinin %22–36’sı).',
        'DPVO görsel odometri, döngü kapatma ve Umeyama hizalamasıyla GPS’siz konum kestirimi: GPS kesildikten sonraki 1.800 karede ~1,6 m yatay hata (yarışma sunucusunun yerel kopyasında).',
        'RGB ve termal video arasında referans nesne eşleştirme (SAM 2 + DINOv3): %98,8 kesinlik.',
        'YOLO26 ile nesne tespiti, PaDiM ile iniş alanı anomali tespiti; araç hareketi doğruluğu 0,946’dan 0,985’e çıkarıldı.',
        'Kök neden düzeltmeleri: süreçler arası atomik kare aktarımı bozuk kareleri %9’dan %0’a indirdi; kalibrasyon güven kapısı en kötü oturumun hatasını 982 m’den 6,4 m’ye düşürdü.',
        'Çevrim içi simülasyon turu: 150’den fazla takımın katıldığı turda 2. (puan 61,12); Eylül 2026’da yerinde final.',
      ],
    },
    stack: ['Python', 'PyTorch', 'YOLO26', 'DPVO', 'SAM 2.1', 'DINOv3', 'PaDiM'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/nuron-teknofest-2026' }],
    cover: { type: 'video', src: '/assets/video/nuron_session4', poster: '/assets/img/poster_nuron_session4.webp' },
    media: [
      {
        type: 'video',
        src: '/assets/video/nuron_session4',
        poster: '/assets/img/poster_nuron_session4.webp',
        alt: {
          en: 'NURON live dashboard during on-site session 4: detections on the aerial frame, GPS status and the X/Y/Z position estimate over time (12 s excerpt)',
          tr: 'Yerinde 4. oturumda NURON canlı paneli: hava karesinde tespitler, GPS durumu ve zaman içinde X/Y/Z konum kestirimi (12 sn kesit)',
        },
      },
      {
        type: 'image',
        src: '/assets/img/nuron_traj_xy.webp',
        alt: { en: 'Session 4 XY trajectory: GPS-anchored calibration leg in green, NURON’s GPS-denied estimate in blue', tr: '4. oturum XY yörüngesi: yeşil GPS’li kalibrasyon bacağı, mavi NURON’un GPS’siz kestirimi' },
      },
      {
        type: 'image',
        src: '/assets/img/nuron_traj_3d.webp',
        alt: { en: 'Session 4 3D trajectory, 2,784 m flown', tr: '4. oturum 3B yörünge, 2.784 m uçuş' },
      },
      {
        type: 'image',
        src: '/assets/img/nuron_gps_error.webp',
        alt: { en: 'Position error plots on the RGB and thermal sessions: X, Y, Z estimate against ground truth, GPS available only for the first 450 frames', tr: 'RGB ve termal oturumlarda konum hatası grafikleri: X, Y, Z kestirimi ve gerçek değer; GPS yalnızca ilk 450 karede' },
      },
      {
        type: 'image',
        src: '/assets/img/nuron_pipeline.webp',
        alt: { en: 'End-to-end pipeline diagram from the final presentation (in Turkish)', tr: 'Final sunumundan uçtan uca boru hattı şeması' },
      },
    ],
  },
  {
    id: 'ghost-cursor',
    featured: true,
    accent: '#f3c35b',
    title: { en: 'Ghost Cursor', tr: 'Ghost Cursor' },
    subtitle: {
      en: 'Voice-operated multi-screen AI agent · TÜBİTAK 2209-B funded research project',
      tr: 'Sesle yönetilen çok ekranlı yapay zekâ ajanı · TÜBİTAK 2209-B destekli araştırma projesi',
    },
    period: { en: 'June 2026 – present', tr: 'Haziran 2026 – devam ediyor' },
    role: {
      en: 'Principal investigator. Academic advisor: Prof. Dr. Cemil Öz · industry advisor: Datazza.',
      tr: 'Proje yürütücüsü. Akademik danışman: Prof. Dr. Cemil Öz · sanayi danışmanı: Datazza.',
    },
    summary: {
      en: 'An AI agent that operates multiple screens from natural-language voice commands: Whisper speech recognition → LLM action planning → UI automation.',
      tr: 'Doğal dildeki sesli komutlarla birden fazla ekranı yöneten yapay zekâ ajanı: Whisper konuşma tanıma → LLM ile eylem planlama → arayüz otomasyonu.',
    },
    bullets: {
      en: [
        'Funded by TÜBİTAK’s 2209-B Industry-Oriented Undergraduate Research programme (2026).',
        'Pipeline: speech recognition (Whisper) → LLM action planning → UI automation across multiple screens.',
        'I am responsible for the system design and implementation, the project budget and the progress/final reports to TÜBİTAK.',
        'Code is not public yet; the project is in progress.',
      ],
      tr: [
        'TÜBİTAK 2209-B Sanayiye Yönelik Lisans Araştırma Projeleri programı tarafından destekleniyor (2026).',
        'Boru hattı: konuşma tanıma (Whisper) → LLM ile eylem planlama → birden fazla ekranda arayüz otomasyonu.',
        'Sistem tasarımı ve uygulamasından, proje bütçesinden ve TÜBİTAK’a sunulan gelişme/sonuç raporlarından sorumluyum.',
        'Kod henüz açık değil; proje devam ediyor.',
      ],
    },
    stack: ['Python', 'Whisper', 'LLM agents', 'UI automation'],
    links: [],
    cover: { type: 'tile', tile: 'voice' },
    media: [{ type: 'tile', tile: 'voice', alt: { en: 'Illustration: voice command → LLM plan → actions on several screens', tr: 'İllüstrasyon: sesli komut → LLM planı → birden fazla ekranda eylemler' } }],
  },
  {
    id: 'dotnote',
    featured: true,
    accent: '#fbc93a',
    title: { en: 'Dotnote', tr: 'Dotnote' },
    subtitle: {
      en: 'Note-taking app for tablets and phones — pen, audio, video and PDF on real pages',
      tr: 'Tablet ve telefonlar için not uygulaması — kalem, ses, video ve PDF gerçek sayfalarda',
    },
    period: { en: '2026 – present', tr: '2026 – devam ediyor' },
    role: {
      en: 'Product owner and architect; built by directing Claude Code agents. Published under my app brand, elifapps.',
      tr: 'Ürün sahibi ve mimar; Claude Code ajanlarını yöneterek geliştirildi. Kendi uygulama markam elifapps altında.',
    },
    summary: {
      en: 'Flutter app with S Pen handwriting, audio and video placed on the page, A4 pages, PDF annotation, PDF/DOCX export, reminders, widgets and Google Drive backup; 10 languages including right-to-left Arabic.',
      tr: 'S Pen el yazısı, sayfaya yerleştirilen ses ve video, A4 sayfalar, PDF üzerine not, PDF/DOCX dışa aktarma, hatırlatıcılar, widget’lar ve Google Drive yedeği; sağdan sola Arapça dâhil 10 dil.',
    },
    bullets: {
      en: [
        'S Pen handwriting, audio/video placed on the page, A4 pages, PDF annotation, PDF/DOCX export, reminders, home-screen widgets and Google Drive backup; 10 languages including right-to-left Arabic.',
        'Built by directing Claude Code agents: I owned the requirements, a competitor analysis of 9 apps, the architecture (a shared package reused across apps; Screen → Provider → Repository → DAO) and on-device testing.',
        '700+ automated tests and 110+ builds tested on a tablet. I use it daily for my lecture notes; a Google Play release is planned.',
      ],
      tr: [
        'S Pen el yazısı, sayfaya yerleştirilen ses/video, A4 sayfalar, PDF üzerine not, PDF/DOCX dışa aktarma, hatırlatıcılar, ana ekran widget’ları ve Google Drive yedeği; sağdan sola Arapça dâhil 10 dil.',
        'Claude Code ajanlarını yöneterek geliştirildi: gereksinimler, 9 uygulamalık rakip analizi, mimari (uygulamalar arasında paylaşılan paket; Screen → Provider → Repository → DAO) ve cihaz üzerinde test bende.',
        '700’den fazla otomatik test, tablette denenen 110’dan fazla derleme. Ders notlarım için her gün kullanıyorum; Google Play yayını planlanıyor.',
      ],
    },
    stack: ['Flutter', 'Dart', 'Riverpod', 'Drift (SQLite)', 'go_router', 'Android / Web', 'Claude Code'],
    links: [
      { kind: 'site', url: 'https://elifapps.com/apps/dotnote/' },
      { kind: 'site', url: 'https://elifapps.com/', label: 'elifapps.com' },
    ],
    cover: { type: 'video', src: '/assets/video/dotnote_write', poster: '/assets/img/poster_dotnote_write.webp' },
    media: [
      {
        type: 'video',
        src: '/assets/video/dotnote_write',
        poster: '/assets/img/poster_dotnote_write.webp',
        alt: { en: 'Dotnote promo film excerpt: handwriting a physics note, typing on paper, highlighting a diagram', tr: 'Dotnote tanıtım filminden kesit: fizik notu yazma, kâğıda yazı yazma, şema üzerinde fosforlu kalem' },
      },
      {
        type: 'video',
        src: '/assets/video/dotnote_logo',
        poster: '/assets/img/poster_dotnote_logo.webp',
        alt: { en: 'Dotnote promo film ending: the pen puts a dot that becomes a star, then the logo', tr: 'Dotnote tanıtım filminin sonu: kalem bir nokta koyuyor, nokta yıldıza dönüşüyor, ardından logo' },
      },
      { type: 'image', src: '/assets/img/dotnote_pdf_handwriting.webp', alt: { en: 'Dotnote on a tablet: handwriting over a PDF', tr: 'Tablette Dotnote: PDF üzerine el yazısı' } },
      { type: 'image', src: '/assets/img/dotnote_audio_on_page.webp', alt: { en: 'Dotnote: an audio recording placed on the page next to the notes', tr: 'Dotnote: notların yanına, sayfaya yerleştirilmiş ses kaydı' } },
      { type: 'image', src: '/assets/img/dotnote_split_view.webp', alt: { en: 'Dotnote: two notes side by side in split view', tr: 'Dotnote: bölünmüş ekranda yan yana iki not' } },
      { type: 'image', src: '/assets/img/dotnote_dark_mode.webp', alt: { en: 'Dotnote in dark mode', tr: 'Dotnote karanlık modda' } },
    ],
  },
  {
    id: 'road-safety',
    accent: '#8fe3c0',
    title: { en: 'Smart Road Safety & Turkish plate OCR', tr: 'Akıllı Yol Güvenliği ve Türkçe plaka OCR' },
    subtitle: {
      en: 'Vehicle, plate and driver pipeline · TEKNOFEST 2026 5G & AI Smart Road Safety',
      tr: 'Araç, plaka ve sürücü boru hattı · TEKNOFEST 2026 5G ve Yapay Zekâ ile Akıllı Yol Güvenliği',
    },
    period: { en: 'March – September 2026', tr: 'Mart – Eylül 2026' },
    role: { en: 'AI & computer vision developer, Team NURON.', tr: 'Yapay zekâ ve bilgisayarlı görü geliştiricisi, NURON takımı.' },
    summary: {
      en: 'An end-to-end pipeline around a single-pass vehicle, licence-plate and driver detector: plate deskewing and reading, vehicle type/colour and driver-behaviour classification.',
      tr: 'Tek geçişli araç, plaka ve sürücü dedektörü etrafında uçtan uca bir boru hattı: plaka düzeltme ve okuma, araç tipi/rengi ve sürücü davranışı sınıflandırması.',
    },
    bullets: {
      en: [
        'Single-pass vehicle, plate and driver detector (YOLO26-OBB); plate deskewing and reading; vehicle type/colour (EfficientNet) and driver-behaviour classification.',
        'Benchmarked three OCR engines on the same 95 plates and picked the best: EasyOCR 10, PaddleOCR 52, fast-plate-ocr 74 correct; ~455 plates/s on CPU.',
        'Preliminary design report: 84 points (threshold 64). Second stage: 103.29 points, 1.71 short of the 105 finals threshold.',
      ],
      tr: [
        'Tek geçişli araç, plaka ve sürücü dedektörü (YOLO26-OBB); plaka düzeltme ve okuma; araç tipi/rengi (EfficientNet) ve sürücü davranışı sınıflandırması.',
        'Aynı 95 plakada üç OCR motoru karşılaştırıldı, en iyisi seçildi: EasyOCR 10, PaddleOCR 52, fast-plate-ocr 74 doğru; CPU’da ~455 plaka/sn.',
        'Ön tasarım raporu: 84 puan (baraj 64). İkinci aşama: 103,29 puan; 105’lik final barajının 1,71 puan altında.',
      ],
    },
    stack: ['YOLO26-OBB', 'EfficientNet', 'fast-plate-ocr', 'ONNX', 'Python'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/turkish-plate-ocr' }],
    cover: { type: 'image', src: '/assets/img/plate_sample.webp' },
    media: [{ type: 'image', src: '/assets/img/plate_sample.webp', alt: { en: 'Annotated plate crop read as 10APL513 with 0.97 confidence', tr: '0,97 güvenle 10APL513 olarak okunan plaka kesiti' } }],
  },
  {
    id: 'arc-agi3',
    accent: '#c6a7ff',
    title: { en: 'ARC-AGI-3 agents', tr: 'ARC-AGI-3 ajanları' },
    subtitle: {
      en: 'LLM-free, dataset-free learners that discover game rules from their own actions',
      tr: 'Oyun kurallarını kendi eylemlerinden keşfeden, LLM’siz ve veri setsiz öğrenen ajanlar',
    },
    period: { en: 'July – September 2026', tr: 'Temmuz – Eylül 2026' },
    role: { en: 'Independent research, solo.', tr: 'Bağımsız araştırma, tek başıma.' },
    summary: {
      en: 'Two learning agents for the ARC-AGI-3 interactive reasoning benchmark — no LLM, no pretrained model, no dataset, no human play traces. Cleared 7 levels across 25 games (random agent: 2).',
      tr: 'ARC-AGI-3 etkileşimli akıl yürütme ölçütü için iki öğrenen ajan — LLM yok, önceden eğitilmiş model yok, veri seti yok, insan oyun izi yok. 25 oyunda 7 seviye geçildi (rastgele ajan: 2).',
    },
    bullets: {
      en: [
        'arc-agi3-agent: emergent shape/event/role tokens, Z3 MaxSAT rule learning over 192 game-neutral predicates (0.84–0.98 held-out accuracy, <0.2 s per rule) and a wrong-elimination exploration strategy.',
        'brain-edge-architecture: a synapse-like “edge” that carries its own usage budget, so exploration emerges from the rule itself — bisimulation, hypervectors, goal hypotheses, world model.',
        'Cleared 7 levels across 25 games (random agent: 2).',
      ],
      tr: [
        'arc-agi3-agent: kendiliğinden oluşan şekil/olay/rol belirteçleri, 192 oyundan bağımsız yüklem üzerinde Z3 MaxSAT kural öğrenme (0,84–0,98 dışarıda tutulan doğruluk, kural başına <0,2 sn) ve yanlış-eleme keşif stratejisi.',
        'brain-edge-architecture: kendi kullanım bütçesini taşıyan sinaps benzeri bir “kenar”; keşif kuralın kendisinden doğuyor — bisimülasyon, hipervektörler, hedef hipotezleri, dünya modeli.',
        '25 oyunda 7 seviye geçildi (rastgele ajan: 2).',
      ],
    },
    stack: ['Python', 'Z3 MaxSAT', 'Program synthesis', 'Hypervectors'],
    links: [
      { kind: 'code', url: 'https://github.com/adembtr/arc-agi3-agent', label: 'arc-agi3-agent' },
      { kind: 'code', url: 'https://github.com/adembtr/brain-edge-architecture', label: 'brain-edge-architecture' },
    ],
    cover: { type: 'image', src: '/assets/img/arc_lp85.webp' },
    media: [{ type: 'image', src: '/assets/img/arc_lp85.webp', alt: { en: 'Recorded run on game lp85: the game frame on the left, the agent’s current reasoning on the right', tr: 'lp85 oyununda kayıtlı koşu: solda oyun karesi, sağda ajanın o anki akıl yürütmesi' } }],
  },
  {
    id: 'mathai',
    accent: '#ffa9a9',
    title: { en: 'MathTransformer', tr: 'MathTransformer' },
    subtitle: { en: 'A ~0.84M-parameter transformer that learns arithmetic from scratch', tr: 'Aritmetiği sıfırdan öğrenen ~0,84 milyon parametreli bir transformer' },
    period: { en: 'January – February 2026', tr: 'Ocak – Şubat 2026' },
    role: { en: 'Solo.', tr: 'Tek başıma.' },
    summary: {
      en: 'Decoder-only transformer with scratchpad reasoning, position coupling and curriculum learning, trained in mixed precision on an 8 GB GPU.',
      tr: 'Karalama defteri akıl yürütmesi, konum eşleme ve müfredat öğrenmesi içeren, 8 GB GPU’da karışık hassasiyetle eğitilmiş yalnızca-kodçözücü transformer.',
    },
    bullets: {
      en: ['Decoder-only transformer, ~0.84M parameters.', 'Scratchpad reasoning, position coupling and curriculum learning.', 'Mixed-precision training on a single 8 GB GPU.'],
      tr: ['Yalnızca-kodçözücü transformer, ~0,84 milyon parametre.', 'Karalama defteri akıl yürütmesi, konum eşleme ve müfredat öğrenmesi.', 'Tek bir 8 GB GPU’da karışık hassasiyetli eğitim.'],
    },
    stack: ['PyTorch', 'Transformers', 'Python'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/mathai' }],
    cover: { type: 'tile', tile: 'math' },
    media: [{ type: 'tile', tile: 'math', alt: { en: 'Illustration: digits flowing through attention layers', tr: 'İllüstrasyon: dikkat katmanlarından akan rakamlar' } }],
  },
  {
    id: 'rag-pdf-qa',
    accent: '#9fd8ff',
    title: { en: 'rag-pdf-qa', tr: 'rag-pdf-qa' },
    subtitle: { en: 'Local multilingual RAG over a PDF library, with page citations', tr: 'PDF kitaplığı üzerinde yerel, çok dilli RAG; sayfa atıflı' },
    period: { en: 'January – February 2026', tr: 'Ocak – Şubat 2026' },
    role: { en: 'Solo.', tr: 'Tek başıma.' },
    summary: {
      en: 'PyMuPDF extraction, overlapping chunks, multilingual MiniLM embeddings and ChromaDB retrieval with source + page citations — all local.',
      tr: 'PyMuPDF ile metin çıkarma, örtüşen parçalar, çok dilli MiniLM gömmeleri ve kaynak + sayfa atıflı ChromaDB araması — tamamen yerel.',
    },
    bullets: {
      en: ['PyMuPDF extraction and overlapping chunking.', 'Multilingual MiniLM embeddings, ChromaDB retrieval.', 'Answers cite the source document and page.'],
      tr: ['PyMuPDF ile çıkarma ve örtüşen parçalama.', 'Çok dilli MiniLM gömmeleri, ChromaDB araması.', 'Yanıtlar kaynak belgeye ve sayfaya atıf verir.'],
    },
    stack: ['Python', 'ChromaDB', 'MiniLM', 'PyMuPDF'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/rag-pdf-qa' }],
    cover: { type: 'tile', tile: 'docs' },
    media: [{ type: 'tile', tile: 'docs', alt: { en: 'Illustration: pages, chunks and a citation', tr: 'İllüstrasyon: sayfalar, parçalar ve bir atıf' } }],
  },
  {
    id: 'whisper-phone',
    accent: '#ffd48a',
    title: { en: 'whisper-phone-dictation', tr: 'whisper-phone-dictation' },
    subtitle: { en: 'Your phone as a wireless push-to-talk mic for a Linux desktop', tr: 'Telefonunuz Linux masaüstü için kablosuz bas-konuş mikrofonu' },
    period: { en: '2026', tr: '2026' },
    role: { en: 'Solo.', tr: 'Tek başıma.' },
    summary: {
      en: 'Local faster-whisper transcription on the desktop, typed into the focused window via xdotool — Turkish by default.',
      tr: 'Masaüstünde yerel faster-whisper transkripsiyonu, xdotool ile odaktaki pencereye yazılır — varsayılan dil Türkçe.',
    },
    bullets: {
      en: ['Push-to-talk from the phone browser; audio goes to the local machine only.', 'faster-whisper transcription on the desktop, no cloud.', 'Text is typed into whatever window has focus (xdotool).'],
      tr: ['Telefon tarayıcısından bas-konuş; ses yalnızca yerel makineye gider.', 'Masaüstünde faster-whisper transkripsiyonu, bulut yok.', 'Metin odaktaki pencereye yazılır (xdotool).'],
    },
    stack: ['Python', 'faster-whisper', 'Linux', 'xdotool'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/whisper-phone-dictation' }],
    cover: { type: 'tile', tile: 'mic' },
    media: [{ type: 'tile', tile: 'mic', alt: { en: 'Illustration: a waveform travelling from a phone to a desktop', tr: 'İllüstrasyon: telefondan masaüstüne giden ses dalgası' } }],
  },
  {
    id: 'servo-hand',
    accent: '#b8f0a0',
    title: { en: 'Arduino servo hand', tr: 'Arduino servo el' },
    subtitle: { en: 'Four-finger servo-driven robotic hand — early prototype', tr: 'Dört parmaklı servo tahrikli robot el — erken prototip' },
    period: { en: 'March – April 2026', tr: 'Mart – Nisan 2026' },
    role: { en: 'Solo.', tr: 'Tek başıma.' },
    summary: {
      en: 'Arduino sketch for a four-finger servo-driven hand with smooth interpolated pose transitions — my first hardware step towards humanoid robotics.',
      tr: 'Pürüzsüz, aradeğerlemeli poz geçişleri olan dört parmaklı servo tahrikli bir el için Arduino kodu — insansı robotiğe ilk donanım adımım.',
    },
    bullets: {
      en: ['Four servo-driven fingers.', 'Smooth interpolated transitions between poses.', 'Early prototype; the hardware side of the humanoid goal.'],
      tr: ['Dört servo tahrikli parmak.', 'Pozlar arasında pürüzsüz, aradeğerlemeli geçişler.', 'Erken prototip; insansı hedefin donanım tarafı.'],
    },
    stack: ['Arduino', 'C++', 'Servo control'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/arduino-servo-hand' }],
    cover: { type: 'tile', tile: 'hand' },
    media: [{ type: 'tile', tile: 'hand', alt: { en: 'Illustration: four servo-driven fingers', tr: 'İllüstrasyon: dört servo tahrikli parmak' } }],
  },
  {
    id: 'library',
    accent: '#a7c8ff',
    title: { en: 'Library Management System', tr: 'Kütüphane Yönetim Sistemi' },
    subtitle: { en: 'PostgreSQL schema with functions & triggers + Streamlit/Plotly dashboard', tr: 'Fonksiyon ve tetikleyicili PostgreSQL şeması + Streamlit/Plotly panosu' },
    period: { en: 'December 2025 – January 2026', tr: 'Aralık 2025 – Ocak 2026' },
    role: { en: 'Database Management Systems course project, Sakarya University.', tr: 'Veri Tabanı Yönetim Sistemleri dersi projesi, Sakarya Üniversitesi.' },
    summary: {
      en: 'Book, member and loan management on a normalised schema with stored functions and triggers, CRUD screens and Plotly dashboards.',
      tr: 'Saklı fonksiyon ve tetikleyicili normalize şema üzerinde kitap, üye ve ödünç yönetimi; CRUD ekranları ve Plotly panoları.',
    },
    bullets: {
      en: ['Normalised PostgreSQL schema with stored functions and triggers.', 'CRUD screens in Streamlit.', 'Reporting dashboards with Plotly.'],
      tr: ['Saklı fonksiyon ve tetikleyicili normalize PostgreSQL şeması.', 'Streamlit ile CRUD ekranları.', 'Plotly ile raporlama panoları.'],
    },
    stack: ['PostgreSQL', 'Streamlit', 'Plotly', 'Python', 'SQL'],
    links: [{ kind: 'code', url: 'https://github.com/adembtr/VTYSPROJE' }],
    cover: { type: 'tile', tile: 'db' },
    media: [{ type: 'tile', tile: 'db', alt: { en: 'Illustration: tables linked by relations', tr: 'İllüstrasyon: ilişkilerle bağlı tablolar' } }],
  },
];

// ---------------------------------------------------------------------------- experience
export const EXPERIENCE = [
  {
    when: { en: 'June 2026 – present', tr: 'Haziran 2026 – devam ediyor' },
    title: { en: 'Principal Investigator — TÜBİTAK 2209-B research project', tr: 'Proje Yürütücüsü — TÜBİTAK 2209-B araştırma projesi' },
    org: { en: 'TÜBİTAK · part-time · Sakarya, hybrid', tr: 'TÜBİTAK · yarı zamanlı · Sakarya, hibrit' },
    text: {
      en: 'Leading “Ghost Cursor”, an industry-oriented undergraduate research project: an AI agent that operates multiple screens from voice commands (Whisper → LLM planning → UI automation). Responsible for the system design and implementation, the budget and the reports to TÜBİTAK.',
      tr: '“Ghost Cursor” sanayiye yönelik lisans araştırma projesini yürütüyorum: sesli komutlarla birden fazla ekranı yöneten yapay zekâ ajanı (Whisper → LLM planlama → arayüz otomasyonu). Sistem tasarımı ve uygulaması, bütçe ve TÜBİTAK raporları benim sorumluluğumda.',
    },
  },
  {
    when: { en: 'March – September 2026', tr: 'Mart – Eylül 2026' },
    title: { en: 'Team Captain & AI Developer — Team NURON', tr: 'Takım Kaptanı ve Yapay Zekâ Geliştiricisi — NURON Takımı' },
    org: { en: 'TEKNOFEST 2026 Artificial Intelligence in Aviation · finalist', tr: 'TEKNOFEST 2026 Havacılıkta Yapay Zekâ · finalist' },
    text: {
      en: 'Selected the models and wrote the algorithms for all three tasks, solved on one frame stream, fully offline on a single 8 GB GPU. 2nd in the online simulation round (score 61.12); on-site finals in September 2026.',
      tr: 'Üç görevin tamamı için modelleri seçtim ve algoritmaları yazdım; tek kare akışında, tamamen çevrim dışı, tek bir 8 GB GPU’da. Çevrim içi simülasyon turunda 2. (puan 61,12); Eylül 2026’da yerinde final.',
    },
  },
  {
    when: { en: 'March – September 2026', tr: 'Mart – Eylül 2026' },
    title: { en: 'AI & Computer Vision Developer — Team NURON', tr: 'Yapay Zekâ ve Bilgisayarlı Görü Geliştiricisi — NURON Takımı' },
    org: { en: 'TEKNOFEST 2026 5G & AI Smart Road Safety', tr: 'TEKNOFEST 2026 5G ve Yapay Zekâ ile Akıllı Yol Güvenliği' },
    text: {
      en: 'Built the vision pipeline around a single-pass vehicle, plate and driver detector; benchmarked three OCR engines on the same 95 plates. Preliminary design report 84 points (threshold 64); second stage 103.29.',
      tr: 'Tek geçişli araç, plaka ve sürücü dedektörü etrafında görü boru hattını kurdum; aynı 95 plakada üç OCR motorunu karşılaştırdım. Ön tasarım raporu 84 puan (baraj 64); ikinci aşama 103,29.',
    },
  },
  {
    when: { en: 'July – September 2026', tr: 'Temmuz – Eylül 2026' },
    title: { en: 'Independent AI Researcher — ARC-AGI-3', tr: 'Bağımsız Yapay Zekâ Araştırmacısı — ARC-AGI-3' },
    org: { en: 'Self-directed · remote', tr: 'Bağımsız · uzaktan' },
    text: {
      en: 'Built two learning agents for the ARC-AGI-3 benchmark with no LLM, no pretrained model and no dataset; cleared 7 levels across 25 games (random agent: 2).',
      tr: 'ARC-AGI-3 ölçütü için LLM’siz, önceden eğitilmiş modelsiz ve veri setsiz iki öğrenen ajan geliştirdim; 25 oyunda 7 seviye geçildi (rastgele ajan: 2).',
    },
  },
];

export const EDUCATION = [
  {
    when: { en: '2024 – 2028 (expected)', tr: '2024 – 2028 (beklenen)' },
    title: { en: 'B.Sc. Computer Engineering', tr: 'Lisans, Bilgisayar Mühendisliği' },
    org: { en: 'Sakarya University · GPA 3.48 / 4.00', tr: 'Sakarya Üniversitesi · GNO 3,48 / 4,00' },
    text: {
      en: 'High Honor List (Fall 2024–25, Fall 2025–26) and Honor List (Spring 2024–25, Spring 2025–26). Courses: Data Structures, Database Management Systems, Object-Oriented Programming, Introduction to Programming (C++), Web Technologies, Automatic Control.',
      tr: 'Yüksek Onur Listesi (2024–25 Güz, 2025–26 Güz) ve Onur Listesi (2024–25 Bahar, 2025–26 Bahar). Dersler: Veri Yapıları, Veri Tabanı Yönetim Sistemleri, Nesneye Yönelik Programlama, Programlamaya Giriş (C++), Web Teknolojileri, Otomatik Kontrol.',
    },
  },
  {
    when: { en: '2026 – 2028', tr: '2026 – 2028' },
    title: { en: 'Minor — Electrical & Electronics Engineering: Control and Automation', tr: 'Yan Dal — Elektrik-Elektronik Mühendisliği: Kontrol ve Otomasyon' },
    org: { en: 'Sakarya University', tr: 'Sakarya Üniversitesi' },
    text: {
      en: 'Taken alongside the B.Sc. to build the control side of robotics. Coursework includes Automatic Control and its laboratory.',
      tr: 'Robotiğin kontrol tarafını kurmak için lisansla birlikte alınıyor. Dersler arasında Otomatik Kontrol ve laboratuvarı var.',
    },
  },
  {
    when: { en: '2018 – 2022', tr: '2018 – 2022' },
    title: { en: 'High School Diploma', tr: 'Lise Diploması' },
    org: { en: 'Cahit Elginkan Anadolu Lisesi · İzmit, Kocaeli', tr: 'Cahit Elginkan Anadolu Lisesi · İzmit, Kocaeli' },
    text: {
      en: 'Placed in Sakarya University Computer Engineering through the national university entrance exam (YKS 2024).',
      tr: 'Ulusal üniversite sınavı (YKS 2024) ile Sakarya Üniversitesi Bilgisayar Mühendisliği’ne yerleştim.',
    },
  },
];

export const HONORS = [
  {
    when: { en: 'July 2026', tr: 'Temmuz 2026' },
    title: { en: 'TEKNOFEST 2026 Artificial Intelligence in Aviation — Finalist', tr: 'TEKNOFEST 2026 Havacılıkta Yapay Zekâ — Finalist' },
    org: { en: 'TEKNOFEST', tr: 'TEKNOFEST' },
    text: {
      en: 'Team NURON (captain): 2nd place in the online simulation round (score 61.12) and qualified for the on-site finals.',
      tr: 'NURON takımı (kaptan): çevrim içi simülasyon turunda 2. (puan 61,12) ve yerinde finallere katılım hakkı.',
    },
  },
  {
    when: { en: 'June 2026', tr: 'Haziran 2026' },
    title: { en: 'TÜBİTAK 2209-B Industry-Oriented Undergraduate Research Grant', tr: 'TÜBİTAK 2209-B Sanayiye Yönelik Lisans Araştırma Desteği' },
    org: { en: 'TÜBİTAK', tr: 'TÜBİTAK' },
    text: {
      en: 'Funded project “Ghost Cursor”: an AI agent that operates multiple screens from voice commands. Principal investigator.',
      tr: 'Desteklenen proje “Ghost Cursor”: sesli komutlarla birden fazla ekranı yöneten yapay zekâ ajanı. Proje yürütücüsü.',
    },
  },
  {
    when: { en: 'Fall 2024–25 · Fall 2025–26', tr: '2024–25 Güz · 2025–26 Güz' },
    title: { en: 'High Honor Certificate (Yüksek Onur Belgesi)', tr: 'Yüksek Onur Belgesi' },
    org: { en: 'Sakarya University', tr: 'Sakarya Üniversitesi' },
    text: { en: '', tr: '' },
  },
  {
    when: { en: 'Spring 2024–25 · Spring 2025–26', tr: '2024–25 Bahar · 2025–26 Bahar' },
    title: { en: 'Honor Certificate (Onur Belgesi)', tr: 'Onur Belgesi' },
    org: { en: 'Sakarya University', tr: 'Sakarya Üniversitesi' },
    text: { en: '', tr: '' },
  },
];

export const SKILLS = [
  { group: { en: 'Programming', tr: 'Programlama' }, items: ['Python', 'C++', 'Dart', 'JavaScript', 'SQL', 'C', 'C#', 'Java'] },
  { group: { en: 'AI & vision', tr: 'Yapay zekâ ve görü' }, items: ['PyTorch', 'OpenCV', 'Ultralytics YOLO', 'SAM 2', 'DINOv3', 'Visual odometry (DPVO)', 'OCR', 'Kalman filtering'] },
  { group: { en: 'Agents & LLMs', tr: 'Ajanlar ve LLM' }, items: ['LLM agents', 'RAG', 'Whisper', 'Z3', 'Claude Code'] },
  { group: { en: 'Mobile, web & data', tr: 'Mobil, web ve veri' }, items: ['Flutter', 'Riverpod', 'HTML / CSS / JS', 'Streamlit', 'PostgreSQL', 'SQLite', 'ChromaDB', 'FAISS'] },
  { group: { en: 'Tools', tr: 'Araçlar' }, items: ['Git / GitHub', 'Linux', 'CUDA', 'Conda', 'Android SDK / adb', 'n8n', 'LaTeX', 'Arduino'] },
  { group: { en: 'Languages', tr: 'Diller' }, items: [{ en: 'Turkish — native', tr: 'Türkçe — ana dil' }, { en: 'English — professional working proficiency', tr: 'İngilizce — profesyonel çalışma yetkinliği' }] },
];
